### ISSUE TITLE
Lookahead parsers

### ISSUE THREAD

**Issue by tmbb** [plataformatec/nimble_parsec#5]
I Think nimble doesn't currently support positive or negative lookahead. I don't think I'm using them much at the moment, but're useful sometimea.

**Comment by josevalim** [comment]
As a general rule, if you want a feature, please provide a complete use case. If you don't have one yet, then it can wait. :)

The reason is, as I said in another issue, I really need to understand the requirements to compile it down to something that relies on binary matching. Unfortunately I cannot simply translate combinators in literature.

Thanks.

**Comment by bitwalker** [comment]
The general application for lookahead is for context-sensitivity when combined with a stateful parser. You know what context you are in based on the state of the parser, and can differentiate between ambiguous grammar using lookahead. You might consider a whitespace-sensitive, expression-based language as an example; you have to track the indentation state, and determine how to deal with the currently parsed expression based on what comes next (whether the current block ends or the expression is continued on the next line), i.e. predictive parsing.

I added a `followed_by` parser at some point to `combine`, which allows a parser to succeed only if it's followed by something else, and doesn't consume the input, and so provides some degree of context-sensitivity, but I'm also not sure if parsing using combinators is really well suited to context-sensitive grammars - personally, I find splitting the lexing and parsing phases for those types of grammars makes them much more tractable, and the code easier to decipher, but I may be biased because I love writing parsers.

I think basic lookahead potentially provides some optimization opportunities as well, because you can hint to the parser compiler that pursuing a branch is only worthwhile if a given parser is followed by something else. Perhaps in practice this means that a parser and the lookahead can be merged somehow to form a single pattern match rather than branching. Perhaps the compiler here already merges things in such a way that branching is cheap and lookahead loses its value? I haven't had time to dig in to it yet, so I'm speculating.

Anyway, wanted to chime in with my two cents :)

**Comment by josevalim** [comment]
A general lookahead/2 has been added to master. It can be used to implement things like followed_by.
