### ISSUE TITLE
Public API for code generation

### ISSUE THREAD

**Issue by wojtekmach** [plataformatec/nimble_parsec#8]
I'd like to ship a parser with a Hex package but want to avoid runtime dependency on NimbleParsec. Another use case recently mentioned is to build a parser and ship it as part of Elixir.

Here's a proof-of-concept project that does this:
1. https://github.com/wojtekmach/datetime_parser/commit/3506e4d1532ffeb7ffdc9822f1ad69facce58a2b#diff-6023be6004fce4718dad3dafb576d258R90

2. https://github.com/wojtekmach/datetime_parser/commit/3506e4d1532ffeb7ffdc9822f1ad69facce58a2b#diff-6023be6004fce4718dad3dafb576d258R1

3. https://github.com/wojtekmach/datetime_parser/commit/3506e4d1532ffeb7ffdc9822f1ad69facce58a2b#diff-5c1478fd160c407f8b7abacf1f0b6bcdR1

Is there/could there be a public API that makes such code generation easier?

**Comment by josevalim** [comment]
You can pass `debug: true` to `defparsec` and it will print the results to stderr. It does not include [this user facing generated function](https://github.com/plataformatec/nimble_parsec/blob/40f7f624b24275906c6e5bb8276f3515d4293a17/lib/nimble_parsec.ex#L66-L100) but you likely wouldn't want to keep it anyway.

There is probably a way to make this easier but it is not currently clear exactly how.

**Comment by josevalim** [comment]
Sorry, I misread the proof of concept. It is a nimble parsec proof of concept, that's great. :D

**Comment by wojtekmach** [comment]
> It does not include this user facing generated function but you likely wouldn't want to keep it anyway.

I think it is worth keeping because otherwise the entry-point is `:name__0/6` which isn't super convenient. And yes, I've seen `debug: true` too. And yes, I do agree that it isn't clear how to make this easier, just wanted to start a discussion :)

**Comment by josevalim** [comment]
A couple thoughts: since the goal is not to depend on nimble_parsec, I don't think we should have a compile.nimble_parsec, as that will effectively depend on nimble_parsec. After all, if the goal is to depend on nimble_parsec, then you can just define the code inline.

I do like the idea of using `.eex` though. So here is my suggestion:

  * Have a simple task that receives the name of a bunch of .eex files. This task must make sure the project is compiled before running
  * The task will evaluate those .eex files and output them to the same location *without* the .eex suffix
  * Introduce a NimbleParsec.Printer that we can autoimport when processing the .eex file. The module will have both defparsec and defparsecp. By providing both, the user can choose if they want a public API or not

What do you think?

Should we also format the generated file automatically if the formatter is available?

**Comment by wojtekmach** [comment]
@josevalim perfect, I'll take a stab at it!

> Should we also format the generated file automatically if the formatter is available?

yup, I already had it in the proof-of-concept
